// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("FsPickler")]
[assembly: AssemblyCopyrightAttribute("© Eirik Tsarpalis.")]
[assembly: AssemblyVersionAttribute("3.2.0")]
[assembly: AssemblyFileVersionAttribute("3.2.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.2.0";
        internal const string InformationalVersion = "3.2.0";
    }
}
