// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FsPickler")]
[assembly: AssemblyProductAttribute("FsPickler")]
[assembly: AssemblyCopyrightAttribute("© Eirik Tsarpalis.")]
[assembly: AssemblyVersionAttribute("1.2.13")]
[assembly: AssemblyFileVersionAttribute("1.2.13")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.2.13";
    }
}
