// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.8.9")]
[assembly: AssemblyFileVersionAttribute("0.8.9")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.8.9";
    }
}
