// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsPickler.Core")>]
[<assembly: AssemblyProductAttribute("FsPickler")>]
[<assembly: AssemblyDescriptionAttribute("A fast serialization framework and pickler combinator library for .NET")>]
[<assembly: AssemblyCopyrightAttribute("© Eirik Tsarpalis.")>]
[<assembly: AssemblyVersionAttribute("4.6")>]
[<assembly: AssemblyFileVersionAttribute("4.6")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsPickler.Core"
    let [<Literal>] AssemblyProduct = "FsPickler"
    let [<Literal>] AssemblyDescription = "A fast serialization framework and pickler combinator library for .NET"
    let [<Literal>] AssemblyCopyright = "© Eirik Tsarpalis."
    let [<Literal>] AssemblyVersion = "4.6"
    let [<Literal>] AssemblyFileVersion = "4.6"
