// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsPickler")>]
[<assembly: AssemblyProductAttribute("FsPickler")>]
[<assembly: AssemblyDescriptionAttribute("A fast serialization framework and pickler combinator library for .NET")>]
[<assembly: AssemblyCopyrightAttribute("© Eirik Tsarpalis.")>]
[<assembly: AssemblyVersionAttribute("5.2.1")>]
[<assembly: AssemblyFileVersionAttribute("5.2.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsPickler"
    let [<Literal>] AssemblyProduct = "FsPickler"
    let [<Literal>] AssemblyDescription = "A fast serialization framework and pickler combinator library for .NET"
    let [<Literal>] AssemblyCopyright = "© Eirik Tsarpalis."
    let [<Literal>] AssemblyVersion = "5.2.1"
    let [<Literal>] AssemblyFileVersion = "5.2.1"
